import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Theme } from "@radix-ui/themes";
import { Box, Flex, Grid } from "@radix-ui/themes";
import AuthProvider from "@/context/AuthProvider";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Theme>
            <Flex>
              <SideBar />
              <Flex direction={"column"} className="w-full" gap="3">
                <Header />
                <Box p="5" className="bg-[#F9F9F9] rounded-2xl">
                  {children}
                </Box>
              </Flex>
            </Flex>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
